version: 2

models:
  - name: trip_fact
    description: "moves data from staging to fact table"
    columns:
      - name: vendor_id
      - name: tpep_pickup_datetime
      - name: tpep_dropoff_datetime
      - name: passenger_count
      - name: trip_distance
      - name: rate_code_id
      - name: store_and_fwd_flag
      - name: pu_location_id
      - name: do_location_id
      - name: payment_type_id
      - name: fare_amount
      - name: extra
      - name: mta_tax
      - name: tip_amount
      - name: tolls_amount
      - name: fare_amount
      - name: extra
      - name: mta_tax
      - name: tip_amount
      - name: tolls_amount
      - name: improvement_surcharge
      - name: total_amount
      - name: congestion_surcharge
      - name: row_hash